name: Generate ASCII Artwork

on: push

jobs:

    build_job_1:
        runs-on: ubuntu-latest
        steps:

        #   - name: Checkout Repo
        #     uses: actions/checkout@v5
        
        #   - name: Checkout Repo Files
        #     run: |
        #      pwd
        #      ls -ltra

        #   - name: Executing shell Script
        #     run: |
        #      chmod +x ascii-script.sh
        #      ./ascii-script.sh
          
        - name: Install Cowsay
          run: sudo apt install cowsay -y

        - name: Execute Cowsay Cmd
          run: cowsay -f dragon "Run for cover, im a Dragon....RAWR" >> dragon.txt

        - name: Upload Dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: Dragon-text-file
            path: dragon.txt

        # - name: Test File exists
        #   run: grep -i "dragon" dragon.txt

        # - name: Read File
        #   run: cat dragon.txt

        # - name: Checkout Repo Files
        #   run: ls -ltra
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        
        - name: Download Dragon text file
          uses: actions/download-artifact@v5
          with:
            name: Dragon-text-file

        - name: Test File exists
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:

        - name: Download Dragon text file
          uses: actions/download-artifact@v5
          with:
            name: Dragon-text-file

        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo "Deploying.... ....... ...."